### ISSUE TITLE
Different font style in search menu and other menu

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#175]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/43cd9ee8-7e9c-4375-95fc-ec7b4fa19f2c)
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/6bd2de86-d098-46a1-9e97-e74095933481)

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/47d352ac-b028-4355-a71f-7f55022cfc5b)

The font and style are unified now
