### ISSUE TITLE
After the drag, show the context search results in the memu

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#191]
event callback

**Comment by xp1632** [comment]
Procedures of providing context for searchmenu triggered by handle drag:

1. we first drag from a handle of a node to an empty place, 
   -an edge line is drawn from the start handle to where our mouse located
2. based on the type of this handle and our start node
   -a searchMenu, which only appears the node that is suitable for start handle/node appears
3. user selected one node in the search menu
    - a new node is created
    - the new node's handle is connected with start node's start handle

Other questions:
1. should 'Add Comment' node appears in search menu?
   - I think currently the answer should be no? Because this creation is triggered from a handle
   - the add comment node should be a function for clicking in the background

**Comment by xp1632** [comment]
![Animation5](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/6de514ef-350f-4483-b16a-22c76f193cf8)

**Comment by xp1632** [comment]
The gist of the whole implementation is :
        1. we first create a whole searchmenu  by drag
	2. we find out how to filter data by rules
	3. we give the filtered treeData to the SearchMenu we created

Now Step 1 is finished, I'm in Step two, and I have two questions:

Q1: Since we agreed to use the search keyword to filter TreeData, what's the keyword for searching?
--------------------------
For example, for a handle named new-in-2, what should we search in the SearchBar, also new-in-2 or handleData.dataType?

The basic type for handle is just source and target, but we also defined dataTypes for handles such as:
exec, integer,float, boolean, string, array

-Is there certain rules for that? How should we define if a node matches the handle we drag from?

Q2: I also checked isValidConnection in useGraph and VPEditor.
---------------------------------
-In useGraph's isValidConnection, we define if the datatype is matched
-Other rules are :
   		-do not connect own source with own target
		-if type not match, ConnectAction.Reject 
		-if maxConnection, ConnectAction.Replace
		-otherwise, ConnectAction.Allowed

---------------
-in VPEditor.tsx, we also have isValidConnection, I don't quite understand here and I'll look into that:

```
  const isFromSource = (): boolean => {
              return gui.connectionStartNodeId.current === connection.source;
            };
            const toNode = isFromSource()
              ? connection.target
              : connection.source;
            const toHandle = isFromSource()
              ? connection.targetHandle
              : connection.sourceHandle;

            const toDom =
              document.querySelector(
                `[data-id="${toNode ?? ''}-${toHandle ?? ''}-target"]`
              ) ??
              document.querySelector(
                `[data-id="${toNode ?? ''}-${toHandle ?? ''}-source"]`
              );
```

**Comment by xp1632** [comment]
**Deep in Connection**

**-we first understand gui.connectingNodeId, the type is RefofObject**
	
	- it's declared in useGui and passed inside of interface IGui
	- in VPEditor, onConnectStart(evt,params), 
		params.nodeId's value is set to gui.connectingNodeId.current
	- and these are params for onConnectStart
	- type OnConnectStartParams = {
		  nodeId: string | null;
		  handleId: string | null;
		  handleType: HandleType | null;
		};
		
	- remember, we can start a connection from any node/handle
	- but it may not be valid, so the nodeId here is just the start node
	- not equal to the sourceNode in a real Connecttion
	
	**We then understand Connection**
	```
	type Connection = {
	  source: string | null;
	  target: string | null;
	  sourceHandle: string | null;
	  targetHandle: string | null;
	};
	```
	
	 
	- in isValidConnection,
	what are isFromSource,toNode,toHandle,toDom 
		-isFromSource means a flag to see if currentStartNodeId is from source of the connection
		
		-For example, we have two nodes, node 10 and node 12
		  _____			_____
		O| 10 |O                O| 12 |O      		
		  -----			-----
		 
		- to clarify, why do we only have two types of handles, because
		-the for each node, we only have two types handle, source and target
		-normally, source handle is on the right as output of the node
			-and also as the source of the connection to other node
		-target handle is on the left, which is the link target for other nodes to connect
		-Like this :
			      _____                 	                       _____
		(target)O| 10 |O(source)		(target)O| 12 |O(source)
		              ------					       ------
		
		- if we try to link node 12 from target handle to node 10's source node
		
		                      +------------------------+                  
			      _____V                 	             | _____
		(target)O| 10 |O(source)		(target)O| 12 |O(source)
		              ------					       ------
		
		- it's not a tradition connection, 
			-because traditionally we'll link from source to target
			-right side of node to left side of node
		
		-however, in this case, it still works because this connection itself is valid
		-For this connection, node10 is source, node 11 is target
			-no matter we link node 12 to node 10, or we link node 10 to node 12
			-it only depends on the handle type in both side of this connection
			-the connection is always source to target
			
		-the only difference is the location of Connection Tooltip
	
	- now we are going through connection in VPEditor's code
	-----------------------------------------------------
		1.onConnectStart()
		  the startnodeId (where we drag from) is set to connectionStartNodeId.current
		
		2. isValidConnection(connection)
			- first the isValidConnection we defined in useGraph is called
				if we get status as false, then return false
			
			-if this connection passed, now we're going to find where this connection end
				and open connectionTip widget there
			
			-How can we get the end handle of a connection? 
				-we could document.querySelector() by the handleName
			
			-How do we know the handleName?
				-there's a certain logic to define the handle name:
				 `[data-id="${toNode ?? ''}-${toHandle ?? ''}-target"]`
				 -here toNode is the NodeId of the node we link to
				 -toHandle is the handleName of the handle we link to
				
				
			```
			const isFromSource = (): boolean => {
              return gui.connectionStartNodeId.current === connection.source;
            };
            const toNode = isFromSource()
              ? connection.target
              : connection.source;
            const toHandle = isFromSource()
              ? connection.targetHandle
              : connection.sourceHandle;
			```
			
			- So in these code, 
			-isFromSource find out if the startNode where we drag from
				is equal to the sourceNode of this connection
			
					   +------------------------+                  
				  _____V                 	    | _____
		(target)O| 10 |O(source)		(target)O| 12 |O(source)
		         ------							 ------
			- In this example, we drag from Node12, the startNodeId is 12
				However the sourceNode of this connection is 10
			
			-So we didn't drag from source, then isFromSource is false,
			-then we are dragging to source when isFromSource is false
			-the params of this connection is 
				connection = {source:'10',sourceHandle:'execOut',target:'12',targetHandle:'exexIn'}
				-connection is not defined by where we drag from, no matter we drag from
				-connection is always source to target, in this case, Node 10 to Node 12
					-even when we first create the connection by dragging from Node 12
				
			-thus toNode=connection.source, in this case, Node 10
			-toHandle = connection.sourceHandle, in this case, Node 10's sourceHandle
			
			```
            const toDom =
              document.querySelector(
                `[data-id="${toNode ?? ''}-${toHandle ?? ''}-target"]`
              ) ??
              document.querySelector(
                `[data-id="${toNode ?? ''}-${toHandle ?? ''}-source"]`
              );
			  
            let bbox: DOMRect | undefined;
            if (toDom) {
              bbox = toDom.getBoundingClientRect();
            }
            gui.openWidget(
              'connectionTip',
              {
                left: bbox?.left ?? 0 + 10,
                top: bbox?.top ?? 0 + 10,
              },
              { connectionStatus: status }
            );
			```
			
			- And this part of code is to get HandleDom by its name and creat Widget Tip around it

**Comment by xp1632** [comment]
Thus, Node Matching Rules:
	-inputs match outputs, and vice verse, here we can check the node's definition
		-just like we check the source or target in isFromSource
		
	-after matching inputs/outputs, find the node which exists the same dataType
		or its dataType is any

**Comment by xp1632** [comment]
**How and where to modify, to get a node's handle data:**

-in TreeItemData, we have id, name, configType, children
	
	- we have nodeConfigsToTreeData,
		-where's the nodeConfig from?
		-in SearchMenu, we used nodeConfigsToTreeData(nodeConfigRegistry.getAllNodeConfigs())
        -where's nodeConfigRegistry from?
		-It's in extension/NodeConfigRegistry.ts
			-here we save node name and its config as Record, like a dictionary
			-  public registerNodeConfig(name: string, node: config): void {
				this.registry[name] = node;
			  }
			 -this is how we register or save a node's configuration
			 -getAllNodeConfigs returns this.registry, which is the whole registry dictionary
 
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/1c2dfe6a-6c3c-4e3e-9147-a5ec95c9b5c5)

-getNodeConfig returns the Config of a certain Node by its name(here the name 
			 is configType)
			 - for example, we have config type as extension1.function1
			 -in getNodeConfig(), we'll get path = name.spilt('.')
			 -and traverse the registry dictionary to find the node
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/fcc2b7f1-6465-4ac3-a4e4-f92067519340)

-And in the treeItemData we returned, there's id, name, configType, children, tooltip, No inputs and outputs data of nodes
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/e635602f-21b5-4dba-b9a5-1c2ed6935105)

So we modify nodeConfigToTreeItemData to also add inputs/outputs handle data to it

**Comment by xp1632** [comment]
**Now we have added the respective inputs and outputs handle information in TreeItemData **
Next step is to:
       - get the input or output; handle's datatype from starthandle
	- search matching node who has opposite input or output
			-and handle has same datatype in SearchTreeView's treedata


![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/da9576ec-997b-4dea-bb14-ab19fcc84a1f)

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/d4c62cab-4944-4c8a-b52e-133fbf3efc98)

For test run of filteredTreeDataWithHandleDataType (item, 'source', 'exec'), we could find the matching node for a source handle with exec dataType

Problem to solve
- The filtered treedata doesn't appear as it should be like in conole, we need further modification
- The handle data we get from onConnectStartParams is:
   		handleParams= {
			"nodeId": "10",
			"handleId": "execOut",
			"handleType": "source"
		}
  here handleId is not handle.dataType, we also need to fetch the dataType somehow

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/c8626302-8910-41e9-85d3-9bb1f3e2657a)

The Reason for filtered Data didn't show properly is that:

- Reason 1, we return true when we find the first child that meet requirements
				-For example, we only find Flow Control-Sequence, howwver,
				-its' sibling Flow Control-If else is omiited because we've returned true

- Reason 2, after the if requirements met, the {...item} we returned
				-is the whole Flow Control data, not a small piece like Flow Control-Squence
					-we may have to return respective child?

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/56981fa1-3e47-4371-98fe-d294a8343220)

The filter function with matching handleType and datatype is correct now, next steps are:

1. to only use this handletype, datatype filter in the searchmenu that triggered by dragging handle, 
    -get the original keyword search back in normal usecase
2. fix the tunnel from onConnectStart's params(handleId, NodeId, handleType) to passing to our filter function
    - how to know handle's dataType needs more work
 3. how to link the node we create in our drag-search-menu with correct handle, and set correct edge
     - matching handle information could be provided by hasMatchingDataType while filtering, how to use it

**Comment by xp1632** [comment]
> ![image](https://user-images.githubusercontent.com/8528052/256515857-56981fa1-3e47-4371-98fe-d294a8343220.png)
> 
> The filter function with matching handleType and datatype is correct now, next steps are:
> 
> Q1. to only use this handletype, datatype filter in the searchmenu that triggered by dragging handle, -get the original keyword search back in normal usecase Q2. fix the tunnel from onConnectStart's params(handleId, NodeId, handleType) to passing to our filter function - how to know handle's dataType needs more work Q3. how to link the node we create in our drag-search-menu with correct handle, and set correct edge - matching handle information could be provided by hasMatchingDataType while filtering, how to use it

Q1 is solved in last commit, Q2 and Q3 needs more thinking

**Comment by xp1632** [comment]
![Animation6](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/89ecb708-e75c-45d5-931e-bdd32d2682b4)

**Comment by xp1632** [comment]
Next Step:

1. find where we can get the handleData.dataType from the handle we drag from

2. build a edge after the user clicks at the filtered TreeItem
   the edge is between our startHandle and user's clicked treeItem's matching handle(the handle with correct handleType and dataType)

**Comment by xp1632** [comment]
![Animation7](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/24ccf5f0-010b-4989-94ba-5bf5dccc03b2)

**Comment by xp1632** [comment]
![Animation8](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/47e73f49-331a-45e2-9db0-ce2aa3739d01)

**Comment by xp1632** [comment]
**The function part is finished for this issue. There are some further enhancements:**

1. When there's no matching node&&handle after dragging, show a hint instead of a blank small menu

2. Move the filter from SearchedTreeView level to SearchMenu level during nodeConfigToTreeData()

3. After that, get the SearchInput for filtered SearchMenu back, avoid conflicts with original keyword-search-filter

**Comment by xp1632** [comment]
Current problems need to be solved:

-Q1,  The reroute node
the reroute node is not in the nodeConfigToTreeData, because usually, the commandToTreeData has no handles
we may need to add something for reroute manually

-Q2, currently the filtering is written for format TreeItemData, however, if we would like to filter config, we need to modify all the filter function for the structure for Configs somehow?

**Comment by xp1632** [comment]
Current Problems:

Q1: the keyword search is conflicted with datatype match filtering,
-might be caused by order of rendering or some other details, need to figure out why

Q2: the add Comment etc is not shown as expected after moving the filtering to SearchMenu
- might need to add reroute's handle condition manually
-

**Comment by xp1632** [comment]
Current Problems:
The original CommandToTreeView Part is lost, need to add it somewhere

**Comment by xp1632** [comment]
> 
Need to clean up SearchMenu's treeData, filteredTreeData.
Add commandToTreeData to the filteredTreeData and pass filteredTreeData to child component

**Comment by xp1632** [comment]
> Current Problems: The original CommandToTreeView Part is lost, need to add it somewhere

> 
Need to clean up SearchMenu's treeData, filteredTreeData.
Add commandToTreeData to the filteredTreeData and pass filteredTreeData to child component

**Comment by xp1632** [comment]
![Animation8](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/058fe564-670f-4fac-8334-1f34395b64c7)
