### ISSUE TITLE
Fix incompatible maxWidth of node and color layer; Change the bottom border of the input

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#235]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/5fcd8137-749d-4af1-b0f1-61e025b3cc5b)

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/56475985-b164-47df-a1bf-6b19d618c0dd)
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/15939d35-cbd2-4a49-8a8e-558d96eb2316)

**Comment by Max-ChenFei** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/f65ad933-9588-42fb-8c01-9b9e0f1c230f)
set the same mini-width and mini-height

**Comment by Max-ChenFei** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/9eef2daa-5e10-49da-8c89-6087e173e9d6)
left-padding vs right -padding @xp1632

**Comment by xp1632** [comment]
> ![image](https://user-images.githubusercontent.com/28513798/251679182-9eef2daa-5e10-49da-8c89-6087e173e9d6.png) left-padding vs right -padding @xp1632

It's not caused by padding, it's caused by color layer overflow 
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/a07b3a28-fa6d-41d4-95ab-1af732537784)

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/77044cd2-9131-491d-a65f-a00abe2c07ce)
This is more obvious, the toolbar is also at the outside of node

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/8511479e-88f4-4105-b68e-24906f6922a8)

**Comment by Max-ChenFei** [comment]
for minWidth, 
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/72b48fbe-b16f-46ed-82e6-0e8c25682cde)
