### ISSUE TITLE
Strong the function name

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#240]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/c37d5c71-406e-483c-8fb2-e327f2cc65ec)

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/aabe4970-359c-45f8-a836-16c7cddd0369)
