### ISSUE TITLE
Find a icon for sticky note

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#243]

**Comment by Max-ChenFei** [comment]
https://www.flaticon.com/free-icon/sticky-note_4434927?term=sticky+note&related_id=4434927

https://www.flaticon.com/free-icon/sticky-note_10303712?term=sticky+note&page=1&position=9&origin=tag&related_id=10303712

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/5adefbbd-56ee-4077-aa7a-0751ae3ff0f6)
