### ISSUE TITLE
css Coherence with jupyter

### ISSUE THREAD

**Issue by xp1632** [Max-ChenFei/VisualProgrammingEditor#263]
We would add some modifications to the internal package:

- [x] Add Fontweight variable for AccordionSummary
- [x] Add HoverEffect to uninstall button in AccordionItem
- [x] Right-aligned  the buttons as well
- [x] Add scrollbar for node extension library

- [x] Delete padding-left and padding-top in NodeExtension
- [x] Fix parts of fontsize issue by using px
- [x] font color of the font in the list and summary

We already add some modification to outer CSS in VP4 project's base.css:

- --vp-ui-font-family: var(--jp-ui-font-family) !important;
  --vp-ui-font-color-blue: var(--jp-content-link-color) !important;

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/05e0a2ba-cde6-40c4-b41b-f4d646df7de7)

**Comment by Max-ChenFei** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/c8a681c1-4d83-4d23-8e8d-2999fe7a1b50)
`disable` not aligned

**Comment by Max-ChenFei** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/51aaed5a-f56b-4719-ab42-2d0e2f6f275c)
not vertically aligned

**Comment by Max-ChenFei** [comment]
not align left for the text
![Esc233247](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/8127daa2-6fc2-4344-b8c0-3698b9da3b0b)

**Comment by xp1632** [comment]
I'll bind font-size of accordion summary title and - var(--jp-ui-font-size1) in VP4 project

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/a51f8e2d-fa91-438d-b654-90f3a0268ba6)
font-size 13px as in jupyter

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/1e375d89-094a-43f1-923c-fbd5499f1fa0)

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/492b3fea-45fd-4484-a877-7e3092e048ad)

**Comment by xp1632** [comment]
Now I'll link to the VP4 to see the final look and use part of jupyter settings

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/5859d00d-b071-4177-84aa-2cbf571b34ef)
Add padding below SearchInput

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/220f8a59-447f-4e36-9b84-f8c015b318db)

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/1e1c5831-a15f-4b13-91bc-2c4139e02a00)
Font fixed in version 8.0.8
