### ISSUE TITLE
Error: ResizeObserver loop limit exceeded when resizing the node

### ISSUE THREAD

**Issue by xp1632** [Max-ChenFei/VisualProgrammingEditor#266]
While solving the maxWidth problem, I find the long-existing problem when resizing the node quite annoying.

So here's some hint of solving it:

1. The cause of this error is:
The `ResizeObserver loop limit exceeded` error can occur when the `ResizeObserver` API is used to observe changes to the size of an element. This error occurs when the `ResizeObserver` callback is called too many times in a short period of time, which can cause the browser to crash.

2. Solution: to use debounce function, or to use requestAnimationFrame
One way to fix this issue is to use a debounce function to limit the number of times the `ResizeObserver` callback is called. However, if the error still persists, you can try using the `requestAnimationFrame` method to throttle the number of times the `ResizeObserver` callback is called.

Here's an example of how you can use `requestAnimationFrame` to throttle the `ResizeObserver` callback:

```typescript
const onResize = useCallback(
  (entries: ResizeObserverEntry[]) => {
    window.requestAnimationFrame(() => {
      const { width, height } = entries[0].contentRect;
      setWidth(width);
      setHeight(height);
    });
  },
  []
);

const resizeObserver = useRef<ResizeObserver | null>(null);

useEffect(() => {
  resizeObserver.current = new ResizeObserver(onResize);
  resizeObserver.current.observe(containerRef.current);

  return () => {
    if (resizeObserver.current) {
      resizeObserver.current.disconnect();
    }
  };
}, [onResize]);
```

In this example, the `onResize` callback is wrapped in a call to `requestAnimationFrame`, which will limit the number of times the callback is called to once per frame. This should help to prevent the `ResizeObserver loop limit exceeded` error from occurring.

**Comment by xp1632** [comment]
But I met some more complicated issues when trying to solve this error, but the method is correct, so I wrote it down as reference

**Comment by xp1632** [comment]
import { debounce } from 'lodash';

function MyComponent() {
  const [width, setWidth] = useState<number>(0);

  useEffect(() => {
    const resizeObserver = new ResizeObserver(
      debounce((entries: ResizeObserverEntry[]) => {
        const { width } = entries[0].contentRect;
        setWidth(width);
      }, 100) // 100ms debounce delay
    );

    resizeObserver.observe(document.body);

    return () => {
      resizeObserver.disconnect();
    };
  }, []);

  return (
    <div>
      <p>Window width: {width}px</p>
    </div>
  );
}

**Comment by xp1632** [comment]
> import { debounce } from 'lodash';
> 
> function MyComponent() { const [width, setWidth] = useState(0);
> 
> useEffect(() => { const resizeObserver = new ResizeObserver( debounce((entries: ResizeObserverEntry[]) => { const { width } = entries[0].contentRect; setWidth(width); }, 100) // 100ms debounce delay );
> 
> ```
> resizeObserver.observe(document.body);
> 
> return () => {
>   resizeObserver.disconnect();
> };
> ```
> 
> }, []);
> 
> return (
> 
> 
> Window width: {width}px
> 
> 
> 
> );
> }

This is the debounce method

**Comment by Max-ChenFei** [comment]
just update the reactflow. Solution is from [here](https://github.com/wbkd/react-flow/issues/3076)

**Comment by Max-ChenFei** [comment]
Check the comment node

**Comment by Max-ChenFei** [comment]
It is fine for build version.
