### ISSUE TITLE
font family?

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#275]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/097996a9-340e-4741-9086-2eeb168f1836)

**Comment by Max-ChenFei** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/a7a1d220-2930-4c73-b61f-d61cd23e1a7d)

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/9f5c4d30-304c-40d6-8507-6658898c5837)

Wrong version?
 @Max-ChenFei

**Comment by xp1632** [comment]
I noticed that the cssEnhancement branch in VP4 project is not merged with the main branch yet, could it be the reason?
