### ISSUE TITLE
Press `Enter` to the item in the search menu to add node

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#305]
- [x] Create Node by pressing Enter
- [x] pass the projected coordinate to `addNode` when using the key down
       -check useScene.ts , how addNode defined with position, and we need to
       pass the anchor coordinate of Search Menu to addNode, so the new Node 
       would be created at correct position
      - we can use useTrackMousePos hook to get mouse Pos

- [x] clear & auto arrange after merge

**Comment by Max-ChenFei** [comment]
after #306

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/6b7ae1e1-af1e-46e3-8075-682fecdace54)
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/a81e0b52-bf90-42e2-b3c8-405ddfea040c)

Currently, As in picture
1. pass prop function from layers of SearchedTreeItem to SearchMenu is finished
2. get the focus item is finished
3. create nodes is finished

However, there are several problems to be solved:

1. The setFoucuedNode we get from onNodeFocus has a 'string' type
2. The createNode function we define in SearchMenu need an item as 'TreeItemData' type
 so we could ignore the items that have children, such as we should ignore 'Variable', but create its child
when its child is activated

 I tried a little bit of using selected prop in Treeview, which says would return selected items ID,
-but I'm not sure if selected== focused
-and how to use this ID to get the TreeItemData we need

**Comment by xp1632** [comment]
**NodeId for TreeItem's nodeId** 

What onFocusNode returned, is actually nodeId of each TreeViewItem

We have two types of id in Search Menu:
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/55d064c4-8b3d-48db-a9bb-5ed653adf377)

-For the TreeData we get from commands in SearchMenu.tsx, we have id the same as its string name:
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/34f98b07-8179-4c3c-94d4-f518390734a7)

-For the TreeData we get from nodeConfig  in SearchedTreeView.tsx, we have id which is number based on itemId++
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/bfc94eff-4e59-4dad-9e55-6eb8ee14fb59)

**Comment by xp1632** [comment]
![Animation4](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/22b2a896-05a7-4014-94ad-6fa7d9c5d6e7)

**Comment by Max-ChenFei** [comment]
> TreeData we get from commands has no configTypes, I'll add it to them in next commit.
> 
> Or do we need configTypes for them?

You can directly get onClick callback

**Comment by xp1632** [comment]
> 

Okay, I'll look into that. I think currently the configType for Comment, StickyNot etc. nodes are set manually in the addNode

**Comment by Max-ChenFei** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/8528052/254385828-da334262-9c56-49c2-bf40-20ba0523c3d4.png)
> 
> Okay, I'll look into that. I think currently the configType for Comment, StickyNot etc. nodes are set manually in the addNode

Here you can see each command definition, there is an action event. and then action will be called when click or press enter key

**Comment by xp1632** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/8528052/254385828-da334262-9c56-49c2-bf40-20ba0523c3d4.png)
> > Okay, I'll look into that. I think currently the configType for Comment, StickyNot etc. nodes are set manually in the addNode
> 
> Here you can see each command definition, there is an action event. and then action will be called when click or press enter key

Okay! Thank you for your explaination! I'll check how to use the action for commands

**Comment by xp1632** [comment]
![Animation5](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/f24f1935-89bf-45f9-ade4-f1dd45e10fd5)

**Comment by xp1632** [comment]
![Animation5](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/371ba92e-b85d-47d9-9524-d88ab36e91a0)
