### ISSUE TITLE
When input in search menu, always trigger keydown event on root

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#327]
![33333](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/9a064289-8edd-4e55-9be4-79459ea6dd69)

**Comment by xp1632** [comment]
![Animation5](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/87db49b4-ea09-46e1-bf53-80b82bf5b516)
In Branch search-menu, we don't have this input trigger node creation bug

**Comment by Max-ChenFei** [comment]
> ![Animation5](https://user-images.githubusercontent.com/8528052/254560153-87db49b4-ea09-46e1-bf53-80b82bf5b516.gif) In Branch search-menu, we don't have this input trigger node creation bug

yes, this is new bug introduced by me yesterday

**Comment by xp1632** [comment]
> > ![Animation5](https://user-images.githubusercontent.com/8528052/254560153-87db49b4-ea09-46e1-bf53-80b82bf5b516.gif)
> >       
> >         [
> >           
> >         
> >             ![Animation5](https://user-images.githubusercontent.com/8528052/254560153-87db49b4-ea09-46e1-bf53-80b82bf5b516.gif)
> >           ](https://user-images.githubusercontent.com/8528052/254560153-87db49b4-ea09-46e1-bf53-80b82bf5b516.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/8528052/254560153-87db49b4-ea09-46e1-bf53-80b82bf5b516.gif)
> >         
> >        In Branch search-menu, we don't have this input trigger node creation bug
> 
> yes, this is new bug introduced by me yesterday

yeah, maybe during merge we would find where the problem is
