### ISSUE TITLE
Handle css when connecting, connected, normal

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#82]
empty or full?
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/d1d6ced9-8d8a-4cc4-a6a4-8bd7409e78d9)

**Comment by xp1632** [comment]
According to Figma: 
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/68101ea5-5e12-45f6-8409-bf0b421cd807)
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/86ac66a9-98fc-4ccf-b941-18f5b298bf5a)

When selecting the node, it's an empty circle with a wide border, to show it's available to connect.

And when the node is connected, the empty circle is filled, to show the connection is successful

**Comment by xp1632** [comment]
> And for normal case, their handle disappears, but I think we should keep ours handle visiable

Or not? just show the arrow direction on the edge

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/96aa1d44-3d57-4338-8dae-952994f27ab6)
connected css class:  .handle_connected
not_connected css class : .handle_not_connected

**Comment by Max-ChenFei** [comment]
color encoded and style

**Comment by xp1632** [comment]
edit in Feat/edge-style, add connected css to connected handle

**Comment by xp1632** [comment]
![image](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/75e99b3a-84da-4e21-842f-cc5a42c3d1b5)
